### ISSUE TITLE
[BUG] Query.bind works incorrectly for boolean values

### ISSUE THREAD

**Issue by caseyryan** [conduit-dart/conduit#130] opened 2022-11-01 03:42 UTC
**Describe the bug**
I've got an endpoint like this
```dart
router.route('/api/v1/dic/search/[:word]').link(
          () => DictionaryController(),
        );
```

And an operation in my controller
```dart
 @Operation.get('word')
  Future<Response> search(
    @Bind.path('word') String word, {
    @Bind.query('excludeSubwords') bool excludeSubwords = false,
    @Bind.query('pinyinizeTranslations') bool pinyinizeTranslations = true,
  }) async {
    ///...
}
```
**To Reproduce**
I send a request from postman
http://127.0.0.1:8888/api/v1/dic/search/洋?excludeSubwords=true&pinyinizeTranslations=false

**Expected behavior**
pinyinizeTranslations == false and excludeSubwords == true

**Actual behavior**
pinyinizeTranslations == true and excludeSubwords == false

**Screenshots**
<img width="898" alt="Screenshot at Nov 01 10-34-04" src="https://user-images.githubusercontent.com/4113558/199153771-4ecbed7b-7e7e-43c7-a877-e19733bef652.png">

It will work correctly for strings. If I replace the declaration for this 

```dart
 @Operation.get('word')
  Future<Response> search(
    @Bind.path('word') String word, {
    @Bind.query('excludeSubwords') String excludeSubwords = '',
    @Bind.query('pinyinizeTranslations') String pinyinizeTranslations = '',
  }) async {
}

```
the strings will be "false" and "true" as expected. So it's definitely an issue in conduit

**Comment by Reductions** [comment] 2022-11-01 09:35
How bool query params are handled in Conduit is if they are present in the query they are treated as `true`. If they are not present they are treated as `false`. So in your case, your query should be:
```
ip/path?excludeSubwords
```
This will result in excludeSubwords=true and pinyinizeTranslations=false

This is not a bug.

**Comment by caseyryan** [comment] 2022-11-01 09:44
Hi. Thanks for the explanation. But it's really inobvious and not the best solution I think. The problem is that you might just use something like this on the frontend 
```dart
Future<DictionaryData?> search({
   required String value,
   bool excludeSubwords = true,
   bool pinyinizeTranslations = false,
}) async {
   return get<DictionaryData>('api/v1/dic/search/洋?excludeSubwords=$excludeSubwords&pinyinizeTranslations=$pinyinizeTranslations');
}
```
So the parameters are always added. 
It's not much of a problem to use some param constructor to make it compatible with conduit but the more people use Conduit the more issues like this will be opened. 

I can fix it and make a pull request if you don't mind changing this functionality

**Comment by Reductions** [comment] 2022-11-07 21:07
You can do the pull request, but there are open questions about what happens if I do:
```
HTTP://whatever.com?pinyinizeTranslations=1
```
or
```
HTTP://whatever.com?pinyinizeTranslations=0
```

You have to think about all the cases.

**Comment by MansonLuo** [comment] 2022-11-21 04:48
(: not a good idea, it's sound like c.

**Comment by MansonLuo** [comment] 2022-11-21 04:52
what's the reason behind make this decision of using exisitence of boo query to express true? that's sound's weird, for newby like me, i nearly think this is a bug before i found this sollution.

**Comment by caseyryan** [comment] 2022-11-21 04:52
> You can do the pull request, but there are open questions about what happens if I do:
> 
> ```
> HTTP://whatever.com?pinyinizeTranslations=1
> ```
> 
> or
> 
> ```
> HTTP://whatever.com?pinyinizeTranslations=0
> ```
> 
> You have to think about all the cases.

Not really, 1 or 0 must be accepted by int params only. If you pass 1 or 0 where a boolean is expected, the better way would be just throw a bad request error. Totally agree with [MansonLuo](https://github.com/MansonLuo) , it's not a c/c++ it's REST

**Comment by j4qfrost** [comment] 2022-11-23 04:11
Going to close this as this appears to be resolved. Not making any changes here.

**Closed by j4qfrost** 2022-11-23 04:11 UTC
Labels: bug
