### ISSUE TITLE
[BUG] Error: Method not found: 'Uuid'.

### ISSUE THREAD

**Issue by mmsdocs** [conduit-dart/conduit#116] opened 2022-10-05 02:37 UTC
**Describe the bug**
I'm trying to generate uuid for a string column default value. But I'm getting the error `Error: Method not found: 'Uuid'.`

**To Reproduce**
1. Create a migration
2. Import uuid package `import 'package:uuid/uuid.dart';`
3. Create const uuid object `const Uuid uuid = Uuid();`
4. Run migration `conduit db upgrade`
5. See the specified error

**Expected behavior**
I would expected to run all my migrations on database with success.

**Screenshots**
![image](https://user-images.githubusercontent.com/19829824/193968761-dd215a07-ed84-494c-8229-56d98e236040.png)
![image](https://user-images.githubusercontent.com/19829824/193968874-ace7f5f9-7970-4a14-b6ef-7680a1a13f78.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Dart SDK version: 2.18.2 (stable) (Tue Sep 27 13:24:11 2022 +0200) on "windows_x64"

**Comment by j4qfrost** [comment] 2022-11-23 03:24
@mmsdocs I can't reproduce the issue with the new version of conduit. I'll keep this issue open for a day and close it if you don't respond.

**Closed** 2022-11-23 03:43 UTC
Labels: bug
